const API_BASE='http://127.0.0.1:8010';let token=sessionStorage.getItem('landslideAdminToken')||'',allReports=[];const STATES=['Assam','Arunachal Pradesh','Manipur','Meghalaya','Mizoram','Nagaland','Sikkim','Tripura'],escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function request(path,options={}){const r=await fetch(API_BASE+path,{...options,headers:{...(options.headers||{}),...(token?{Authorization:'Bearer '+token}:{})}}),b=await r.json();if(!r.ok)throw Error(b.detail||'Request failed');return b}
async function login(){const m=document.getElementById('loginMessage');m.textContent='Signing in…';try{token=(await request('/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('password').value})})).token;sessionStorage.setItem('landslideAdminToken',token);await refreshReports()}catch(e){m.className='error';m.textContent=e.message}}
function logout(){token='';allReports=[];sessionStorage.removeItem('landslideAdminToken');document.getElementById('reportsCard').hidden=true;document.getElementById('loginCard').hidden=false}
async function refreshReports(){document.getElementById('loginCard').hidden=true;document.getElementById('reportsCard').hidden=false;document.getElementById('reports').textContent='Refreshing command queue…';try{allReports=await request('/admin/reports');renderReports();loadDataHealth()}catch(e){logout();document.getElementById('loginMessage').className='error';document.getElementById('loginMessage').textContent=e.message}}
async function loadDataHealth(){const box=document.getElementById('adminDataHealth');try{const h=await request('/data-health');box.textContent=`Weather data health: ${h.fresh_locations}/${h.monitored_locations} fresh within ${h.fresh_within_minutes} min · stale: ${h.stale_locations} · missing: ${h.missing_locations} · fallbacks: ${h.fallback_locations} · ${h.overall_status}`;}catch(_){box.textContent='Weather data-health endpoint unavailable.'}}
function priority(r){return r.severity==='HIGH'||r.people_at_risk>0}
function renderReports(){const q=document.getElementById('adminSearch')?.value.toLowerCase()||'',f=document.getElementById('adminFilter')?.value||'ALL',shown=allReports.filter(r=>{const text=`${r.reference_id||''} ${r.incident_type||''} ${r.description||''} ${r.verification_status||''} ${r.delivery_status||''}`.toLowerCase(),match=f==='ALL'||f==='HIGH'&&priority(r)||f==='UNVERIFIED'&&(r.verification_status||'UNVERIFIED')==='UNVERIFIED'||f==='QUEUED'&&(r.delivery_status||'').includes('QUEUED')||f==='SENT'&&(r.delivery_status||'').includes('SENT');return text.includes(q)&&match});document.getElementById('metricTotal').textContent=allReports.length;document.getElementById('metricUrgent').textContent=allReports.filter(priority).length;document.getElementById('metricUnverified').textContent=allReports.filter(r=>(r.verification_status||'UNVERIFIED')==='UNVERIFIED').length;document.getElementById('metricQueued').textContent=allReports.filter(r=>(r.delivery_status||'').includes('QUEUED')).length;const box=document.getElementById('reports');if(!shown.length){box.textContent='No reports match the selected command filter.';return}box.innerHTML=shown.map(card).join('');shown.forEach(r=>{const s=document.getElementById('status-'+r.id);if(s)s.value=r.verification_status||'UNVERIFIED';if(r.reference_id)addPhoto(r)})}
function card(r){const ref=escapeHtml(r.reference_id||'Legacy report'),arg=escapeHtml(r.reference_id||''),opts=STATES.map(s=>`<option ${s===r.dispatch_state?'selected':''}>${s}</option>`).join('');return `<article class="report${priority(r)?' high':''}"><b>${ref}</b> <span class="status">${escapeHtml(r.verification_status||'UNVERIFIED')}</span><p>${escapeHtml(r.incident_type||'LANDSLIDE')} · Severity: <b>${escapeHtml(r.severity)}</b> · People at risk: ${escapeHtml(r.people_at_risk||0)}<br>${escapeHtml(r.description||'No description')}</p><div class="meta">Location: ${escapeHtml(r.lat)}, ${escapeHtml(r.lon)} · Submitted: ${escapeHtml(r.time)}</div><div id="photo-${r.id}"></div><label>Verification status<select id="status-${r.id}"><option>UNVERIFIED</option><option>VERIFIED</option><option>REJECTED</option><option>RESOLVED</option></select></label><label>Verification / audit note<textarea id="note-${r.id}" maxlength="500">${escapeHtml(r.admin_note||'')}</textarea></label><button onclick="updateReport('${arg}',${r.id})">Save verification</button>${r.reference_id?`<div class="dispatch-box"><label>Route to approved official recipient in<select id="dispatch-state-${r.id}">${opts}</select></label><label>Routing note (audit only)<textarea id="dispatch-note-${r.id}" maxlength="500">${escapeHtml(r.dispatch_note||'')}</textarea></label><button onclick="queueDispatch('${arg}',${r.id})">Queue for authority dispatch</button><button class="dispatch-send" onclick="dispatchReport('${arg}')">Send queued report</button><small>Delivery: ${escapeHtml(r.delivery_status||'RECEIVED_LOCALLY_NOT_DISPATCHED')}</small></div>`:''}</article>`}
async function addPhoto(r){if(!r.photo_filename)return;try{const response=await fetch(API_BASE+'/admin/reports/'+encodeURIComponent(r.reference_id)+'/photo',{headers:{Authorization:'Bearer '+token}});if(!response.ok)return;const img=document.createElement('img');img.className='report-photo';img.alt='Private incident report photo';img.src=URL.createObjectURL(await response.blob());document.getElementById('photo-'+r.id)?.appendChild(img)}catch(_){}}
async function updateReport(ref,id){if(!ref)return alert('Legacy report has no reference ID.');const m=document.getElementById('reportMessage');try{await request('/admin/reports/'+encodeURIComponent(ref),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:document.getElementById('status-'+id).value,note:document.getElementById('note-'+id).value})});m.className='success';m.textContent='Verification saved and audit record written.';await refreshReports()}catch(e){m.className='error';m.textContent=e.message}}
async function queueDispatch(ref,id){const m=document.getElementById('reportMessage');try{const d=await request('/admin/reports/'+encodeURIComponent(ref)+'/queue-dispatch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:document.getElementById('dispatch-state-'+id).value,note:document.getElementById('dispatch-note-'+id).value})});m.className='success';m.textContent=d.message+(d.recipient_configured?' Approved recipient configured.':' Recipient not configured; external send stays blocked.');await refreshReports()}catch(e){m.className='error';m.textContent=e.message}}
async function dispatchReport(ref){if(!confirm('Send this unverified report to the configured official recipient?'))return;const m=document.getElementById('reportMessage');try{m.className='success';m.textContent=(await request('/admin/reports/'+encodeURIComponent(ref)+'/dispatch',{method:'POST'})).message;await refreshReports()}catch(e){m.className='error';m.textContent=e.message}}
if(token)refreshReports();
